spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-user?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  application:
    name: user-service
server:
  port: 8082
eureka:
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: user-service
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/lee/userservice/mapping/*.xml
